name: Build and Push Tor Plugin Binary Docker Image (Daily)

on:
  schedule:
    - cron: "0 22 * * *"  # Daily at 10 PM (UTC)
  workflow_dispatch:
    inputs:
      trigger-build:
        description: "Trigger a manual build and push"
        default: "true"

jobs:
  build_and_push_multiarch:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      # Checkout
      - name: Checkout code from target branch
        uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'

      # Docker Hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Buildx
      - name: Set up Docker Buildx (Multi-Arch Builder)
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7

      # QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7

      # Build & Push with Cache Enabled
      - name: Build and Push Tor Plugin Binary Docker Image (Multi-Arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            noxcis/tor-bins:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7

          # --- Enable caching ---
          cache-from: type=registry,ref=noxcis/tor-bins:latest
          cache-to: type=inline
